import type { Metadata } from "next";
// تم حذف: import { Geist, Geist_Mono } from "next/font/google"; 
import "./globals.css";

// تم حذف تعريفات الخطوط

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // تم تغيير لغة الصفحة واتجاهها إلى العربية
    <html lang="ar" dir="rtl">
      {/* تم حذف متغيرات الخطوط من الكلاس */}
      <body className={`antialiased bg-gray-100`}> 
        {children}
      </body>
    </html>
  );
}